### ISSUE TITLE
Expression Biopsy

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#34] opened 2016-07-08 20:26 UTC
@jbphet  I can't make this happen with coins, so use variables for this procedure.

On a touch screen:
1. Make an expression
2. Place your finger above the expression
3. Slowly move your finger down, and use touchSnag to grab a term

https://drive.google.com/file/d/0B5V5jeifFYeSVkNuNFRQQUJsM0k/view?usp=sharing

Details:
- again, I've only been successful with variables
- again, you must move your finger relatively slowly, too fast and the reliability of reproducing decreases
- you must approach the expression in such a way that the top boundary of the expression is the first boundary your finger crosses. In other words, you cannot perform this issue by approaching from the bottom or sides
- I'm not sure, but it seems there is a better chance to reproduce if you grab the variable itself, not its coefficient
- there is **NO** thrown assertion when placing a term back into the expression (no duplicate). Technically, I don't think you can add it back...it seems to have never left

(happened on Win 10, all browsers, and iOS 9.3.2)

**Comment by phet-steele** [comment] 2016-07-08 21:16
> there is NO thrown assertion when placing a term back into the expression (no duplicate). Technically, I don't think you can add it back...it seems to have never left

@jbphet I can't get the error because you removed the assertion :) (maybe in #11?)

**Comment by jbphet** [comment] 2016-07-20 22:32
This is due to a slight protrusion of the touch and mouse areas from the bounds of the expression.  Here is a screenshot from the latest dev version, http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.14/expression-exchange_en.html:

![ex-ex-pointer-areas](https://cloud.githubusercontent.com/assets/3082831/17005284/a3bd57de-4e96-11e6-8c0c-f2b1d01c8751.PNG)

This was probably introduced during some recent changes where the baseline of the text in the coin term nodes was adjusted.  I've addressed the issue by reducing the dilation of the touch areas, moving the baseline down a touch, and slightly increasing the inset in the expression.

Assigning to @phet-steele to verify that this is fixed in master.

**Comment by jbphet** [comment] 2016-07-20 22:33
By the way, here's a post-fix screen shot:

![ex-ex-pointer-areas-fixed](https://cloud.githubusercontent.com/assets/3082831/17005475/a8b4ec9c-4e97-11e6-8b6f-aceb2e3325a9.PNG)

**Comment by amanda-phet** [comment] 2016-07-21 16:12
Quick question: can I request that touch areas extend a bit more below the terms? On a touch device it might be nice to be able to drag a term without having to completely cover the term.

**Comment by phet-steele** [comment] 2016-07-25 16:42
@jbphet I'll wait to test after you are done changing touch areas.

**Comment by jbphet** [comment] 2016-09-21 18:51
I have finished adjusting pointer areas such that they don't protrude from expressions.  @phet-steele - please test and indicate whether the issue appears to be resolved.

@amanda-phet - I shifted the pointer areas down as much as possible without having them protrude from the expression.  Please test this once the rest of the issue is resolved.  If you'd like further work done on this, please open another issue.

**Comment by amanda-phet** [comment] 2016-09-28 18:17
@jbphet Is it possible to publish a dev version or can you include a screenshot of the touch bounds?

**Comment by jbphet** [comment] 2016-09-28 21:53
I just published a dev version, please see http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.0.0-dev.15/expression-exchange_en.html, but the bounds still poke out of the bottom just a little, so I'll need to adjust them a bit.  They will look like they do in this version but just a little bit smaller in the vertical direction.

**Comment by jbphet** [comment] 2016-09-29 23:15
I've adjust the point areas again, and hopefully they are good to do now.

If this doesn't work, I may want to consider reducing the touch areas when a coin term is inside an expression.  Right now this would be a bit tricky, because coin terms are not aware of being in an expression, but that could be changed.

**Comment by amanda-phet** [comment] 2016-10-10 21:52
The pointer areas on the explore screen are a little funny for 2x and 3y. 
![screen shot 2016-10-10 at 3 48 15 pm](https://cloud.githubusercontent.com/assets/7852916/19252323/86b1081a-8f01-11e6-80c2-5a2cad107c66.png)

Also, is there a reason for the pointer areas being different for the break-apart and edit buttons? I would make both buttons have the smaller pointer area for a mouse cursor and larger only for touch. 
![screen shot 2016-10-10 at 3 48 47 pm 2](https://cloud.githubusercontent.com/assets/7852916/19252324/8a634a4a-8f01-11e6-9fdd-461b3fb86dde.png)

I can't see the areas for coins, but with my cursor I was able to roughly identify the bounds and they did not seem too big to me (within an expression- they seemed to go to the edge of the coin and include the coefficient if there was one).

**Comment by jbphet** [comment] 2016-10-12 15:38
@amanda-phet 

> The pointer areas on the explore screen are a little funny for 2x and 3y.

On which version were you testing?  I've adjusted these on master, but the changes would not yet be reflected in the current dev version (1.0.0-dev.16).

> I can't see the areas for coins

The pointer areas for coins are not extended, so they just match the boundary of the nodes themselves.

>  [I]s there a reason for the pointer areas being different for the break-apart and edit buttons? I would make both buttons have the smaller pointer area for a mouse cursor and larger only for touch. 

Good eye!  I've removed the extended mouse area for the break apart button.

**Comment by amanda-phet** [comment] 2016-10-12 17:29
I was testing on dev.15. Sounds like it is fixed now so that's all that matters! 

Can we close this issue?

**Comment by jbphet** [comment] 2016-10-14 17:29
Yes, I think we've covered it.  Closing.

**Closed by jbphet** 2016-10-14 17:29 UTC
Labels: type:bug
