### ISSUE TITLE
Reward Screen will not appear twice

### ISSUE THREAD

**Issue by EthanWJohnson** [phetsims/expression-exchange#115] opened 2017-06-20 20:58 UTC
Unsure if this is intended behavior or not, so reporting in case it isn't. If you complete all the levels on the game screen, reset it, and then complete all the levels again, the final reward screen won't trigger again. It seems it will only ever trigger once without fully reloading the sim.

Seen in Win 10 Chrome

Related to https://github.com/phetsims/tasks/issues/860

Debug Info: 
Name: ‪Expression Exchange‬
URL: http://www.colorado.edu/physics/phet/dev/html/expression-exchange/1.1.0-dev.3/expression-exchange_en.html?
Version: 1.1.0-dev.3 2017-06-13 18:51:38 UTC
Features missing: touch
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/58.0.3029.110 Safari/537.36
Language: en-US
Window: 1680x930
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4096
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {"assert":{"sha":"5c3f9204","branch":"master"},"axon":{"sha":"045bd1b0","branch":"master"},"babel":{"sha":"6d9fa297","branch":"master"},"brand":{"sha":"c904b097","branch":"master"},"chipper":{"sha":"80ae1f14","branch":"master"},"dot":{"sha":"6b4ec39c","branch":"master"},"expression-exchange":{"sha":"5d9ee7b4","branch":"master"},"joist":{"sha":"b35547e9","branch":"master"},"kite":{"sha":"7d2df183","branch":"master"},"phet-core":{"sha":"76ec0204","branch":"master"},"phetcommon":{"sha":"ca2f62cd","branch":"master"},"query-string-machine":{"sha":"c74e454e","branch":"master"},"scenery":{"sha":"c2248424","branch":"master"},"scenery-phet":{"sha":"01067d19","branch":"master"},"sherpa":{"sha":"812fdf9e","branch":"master"},"sun":{"sha":"32cc2197","branch":"master"},"tandem":{"sha":"7b8b8188","branch":"master"},"vegas":{"sha":"45acc1de","branch":"master"},"vibe":{"sha":"5e8151e1","branch":"master"}}

**Comment by phet-steele** [comment] 2017-06-20 21:24
@EthanWJohnson it is not intended behavior and has been reported here: https://github.com/phetsims/expression-exchange/issues/85#issuecomment-309509794. Closing.

**Closed by phet-steele** 2017-06-20 21:24 UTC
Labels: type:bug
