### ISSUE TITLE
Assertion failed: Setting center is invalid when the node has invalid (empty/NaN/infinite) bounds.

### ISSUE THREAD

**Issue by phet-steele** [phetsims/expression-exchange#127] opened 2017-08-07 17:28 UTC
@jbphet this is a very rare error on Bayes.

```
Uncaught Error: Assertion failed: Setting center is invalid when the node has invalid (empty/NaN/infinite) bounds.
Error: Assertion failed: Setting center is invalid when the node has invalid (empty/NaN/infinite) bounds.
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1502069964988/assert/js/assert.js:22:13)
    at BreakApartButton.setCenter (https://bayes.colorado.edu/continuous-testing/snapshot-1502069964988/scenery/js/nodes/Node.js?bust=1502073274698:2669:17)
    at BreakApartButton.set center [as center] (https://bayes.colorado.edu/continuous-testing/snapshot-1502069964988/scenery/js/nodes/Node.js?bust=1502073274698:2675:32)
    at ConstantCoinTermNode.hideBreakApartButton (https://bayes.colorado.edu/continuous-testing/snapshot-1502069964988/expression-exchange/js/common/view/AbstractCoinTermNode.js?bust=1502073274698:204:38)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1502069964988/expression-exchange/js/common/view/AbstractCoinTermNode.js?bust=1502073274698:180:14
    at Array.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1502069964988/phet-core/js/Timer.js?bust=1502073274698:46:11)
    at Object.step (https://bayes.colorado.edu/continuous-testing/snapshot-1502069964988/phet-core/js/Timer.js?bust=1502073274698:32:36)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1502069964988/joist/js/Sim.js?bust=1502073274698:825:13)
    at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/snapshot-1502069964988/joist/js/Sim.js?bust=1502073274698:769:16)
```

**Comment by jbphet** [comment] 2017-08-08 17:43
I've analyzed the stack trace, and this issue is occurring when a timer goes off that is supposed to hide a button that is used to break apart a composite coin term.  The code tries first to position the button, then make it invisible, and the assertion is occurring during the positioning step.

The code *does* check to verify that the button exists before trying to position it, so it's a bit of a mystery why this error occurs.  I've added some additional diagnostic code to verify that the bounds of the button are finite and non-empty, and if either of these conditions are encountered, additional information will be logged to the console.

@phet-steele - please record whatever output is seen the next time this error occurs.

**Comment by phet-steele** [comment] 2017-08-22 15:57
@jbphet, don't think I've ever seen the error checking for checking if bounds are finite, only empty:

```
Error: Assertion failed: break apart button bounds are empty, this.breakApartButton.bounds = 
    at window.assertions.assertFunction (https://bayes.colorado.edu/continuous-testing/snapshot-1503233212900/assert/js/assert.js:22:13)
    at VariableCoinTermNode.hideBreakApartButton (https://bayes.colorado.edu/continuous-testing/snapshot-1503233212900/expression-exchange/js/common/view/AbstractCoinTermNode.js?bust=1503253027413:207:19)
    at https://bayes.colorado.edu/continuous-testing/snapshot-1503233212900/expression-exchange/js/common/view/AbstractCoinTermNode.js?bust=1503253027413:180:14
    at Array.callback (https://bayes.colorado.edu/continuous-testing/snapshot-1503233212900/phet-core/js/Timer.js?bust=1503253027413:46:11)
    at Object.step (https://bayes.colorado.edu/continuous-testing/snapshot-1503233212900/phet-core/js/Timer.js?bust=1503253027413:32:36)
    at Sim.stepSimulation (https://bayes.colorado.edu/continuous-testing/snapshot-1503233212900/joist/js/Sim.js?bust=1503253027413:828:13)
    at Sim.runAnimationLoop (https://bayes.colorado.edu/continuous-testing/snapshot-1503233212900/joist/js/Sim.js?bust=1503253027413:772:16)
Approximately 8/20/2017, 6:46:52 AM
```

**Comment by jbphet** [comment] 2017-11-15 20:53
I dug into this a bit more, and was able to catch it in the Chrome dev tools by doing an overnight fuzz test.  However, while I have more information, I still don't understand how it is happening.  Here is what I can tell:
+ The timer function to hide the button is being called after the button has been disposed
+ The scene graph parent, which in the instance caught in the debugger was a VariableCoinTermNode, had been removed from the scene graph
+ The parent VariableCoinTermNode had a typeID of "X" and a composition of [2, 1, 1], which would seem to imply that it had been on the game screen, since that's the only screen that uses minimum decomposition values greater than 1
+ I can artificially force this issue to occur by commenting out the call to `clearHideButtonTimer` in `AbstractCoinTermNode.disposeAbstractCoinTermNode` and then creating a combined coin term and then dragging it into the carousel

For reference, here is a stack trace for when this occurred.  I'm not sure why it appears so deeply nested with calls to `runAnimationLoop`, but I'll follow up on this separately.

```
window.assertions.assertFunction (assert.js:22)
hideBreakApartButton (AbstractCoinTermNode.js?bust=1510702515939:211)
(anonymous) (AbstractCoinTermNode.js?bust=1510702515939:184)
callback (Timer.js?bust=1510702515939:46)
step (Timer.js?bust=1510702515939:32)
stepSimulation (Sim.js?bust=1510702515939:790)
stepOneFrame (Sim.js?bust=1510702515939:741)
runAnimationLoop (Sim.js?bust=1510702515939:724)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
requestAnimationFrame (async)
runAnimationLoop (Sim.js?bust=1510702515939:718)
```

**Comment by jbphet** [comment] 2017-11-17 23:17
The root cause of this issue is that in some cases when the `userControllerProperty` of a coin term is set to false (i.e. the user releases it) and the break-apart button is showing, one of the handlers for the change of the user controlled property removes the coin term node from the scene graph, and then a later handler tries to update the break-apart button.  However, since the button was disposed by the time that handler is reached, an error occurs.  I've fixed this by adding a check for `isDisposed` to the handler for changes to `userControlledProperty`.  I'll unassign this for now, but will put a reminder on my calendar to check in a week or so and, if I don't see any sign of the problem in automated test, I'll close the issue.

**Comment by jbphet** [comment] 2017-11-20 20:19
The sim has passed continuous test for a while now without the problem showing up, here is an edited screenshot:

![exex-bayes](https://user-images.githubusercontent.com/3082831/33039510-6928ab66-cdf5-11e7-87d0-37f14cc3f84e.PNG)

Closing, will reopen if the issue pops up again.

**Closed by jbphet** 2017-11-20 20:19 UTC
Labels: type:automated-testing, type:bug
